### ISSUE TITLE
pai list-storages question

### ISSUE THREAD

**Issue by tangyetangye** [microsoft/openpaisdk#53]
(base) xxxxx@xxxxx-optiplex-3050:~$ pai list-storages admin
TypeError: this.executors[cmd] is not a function
    at CliEngine.evaluate (/home/ecovacs/myenv/lib/node_modules/@microsoft/openpai-js-sdk/lib/src/commands/cliEngine.js:130:65)
    at /home/ecovacs/myenv/lib/node_modules/@microsoft/openpai-js-sdk/lib/src/cli.js:15:30

**Comment by yiyione** [comment]
@tangyetangye Can you try to remove the cluster and re-add it ? (use `pai delc` and `pai addc`)
